Add missing include for std::find
Without this, the compilation fails with :
wdt/test/EncryptionTest.cpp:76:57: error: no matching function for call to 'find(std::vector<std::__cxx11::basic_string<char> >::iterator, std::vector<std::__cxx11::basic_string<char> >::iterator, std::string&)'

Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>