Add missing include for std::find (#210)
Summary:
Without this, the compilation fails with :
wdt/test/EncryptionTest.cpp:76:57: error: no matching function for call to 'find(std::vector<std::__cxx11::basic_string<char> >::iterator, std::vector<std::__cxx11::basic_string<char> >::iterator, std::string&)'

Signed-off-by: Nicolas Chauvet <kwizart@gmail.com>

Pull Request resolved: https://github.com/facebook/wdt/pull/210

Reviewed By: claudiozz

Differential Revision: D24869824

Pulled By: davide125

fbshipit-source-id: 78777f76f0bee7f3fd9d0d6362d7673b9f7c0f13