fix for change in folly and for sierra macos compile
Summary:
avoids:
/Users/ldemailly/github/wdt/../folly/folly/portability/Time.h:32:17:
error: typedef redefinition with different types ('uint8_t' (aka
'unsigned char') vs 'enum clockid_t')
typedef uint8_t clockid_t;
^
/usr/include/time.h:171:3: note: previous definition is here
} clockid_t;
^

and

Undefined symbols for architecture x86_64:
"folly::ScopeGuardImplBase::warnAboutToCrash()", referenced from:

folly::ScopeGuardImpl<facebook::wdt::ClientSocket::connect()::$_0>::~Sco
peGuardImpl() in ClientSocket.cpp.o
Closes https://github.com/facebook/wdt/pull/134

Differential Revision: D4234290

Pulled By: ldemailly

fbshipit-source-id: bb4a66e4ab31d677865f982ad24aea92e2b04ef3